version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - chatnet

  redis:
    image: redis
    networks:
      - chatnet

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    networks:
      - chatnet

networks:
  chatnet:
